// Generated automatically by nearley, version 2.13.0
// http://github.com/Hardmath123/nearley
(function () {
function id(x) { return x[0]; }
var grammar = {
    Lexer: undefined,
    ParserRules: [
    {"name": "start", "symbols": ["comment"]},
    {"name": "start", "symbols": ["_", "block", "_"]},
    {"name": "block", "symbols": ["comment"]},
    {"name": "block$ebnf$1$subexpression$1$ebnf$1", "symbols": ["NL"]},
    {"name": "block$ebnf$1$subexpression$1$ebnf$1", "symbols": ["block$ebnf$1$subexpression$1$ebnf$1", "NL"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "block$ebnf$1$subexpression$1", "symbols": ["exp", "block$ebnf$1$subexpression$1$ebnf$1"]},
    {"name": "block$ebnf$1", "symbols": ["block$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "block$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "block$ebnf$2$subexpression$1$ebnf$1", "symbols": ["NL"]},
    {"name": "block$ebnf$2$subexpression$1$ebnf$1", "symbols": ["block$ebnf$2$subexpression$1$ebnf$1", "NL"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "block$ebnf$2$subexpression$1", "symbols": ["fromTransition", "block$ebnf$2$subexpression$1$ebnf$1"]},
    {"name": "block$ebnf$2", "symbols": ["block$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "block$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "block", "symbols": ["block$ebnf$1", "block$ebnf$2", "scene"], "postprocess": 
        (data) => {
            let block = {
                type: "state",
                shouldStart:  data[0],
                blockDepth: data[2], // data[1] is "NL:+"
                fromTransition: data[3],
                toTransition: data[11]
            }
            //TODO: figure out how to parse conditionals
            if(data[6] == "scene"){
              block.scene = data[6]
            } else {
              block.blocks = data[6]
            }
            return block
        }
        },
    {"name": "exp", "symbols": ["var"]},
    {"name": "exp", "symbols": ["exp", "AND", "exp"], "postprocess": ([lhs, _, rhs]) => AND(lhs, rhs)},
    {"name": "exp", "symbols": ["exp", "OR", "exp"], "postprocess": ([lhs, _, rhs]) => OR(lhs, rhs)},
    {"name": "exp", "symbols": ["AWAIT", "exp"], "postprocess": id},
    {"name": "exp", "symbols": ["INPUT", "exp"], "postprocess": ([_, rhs]) => INPUT(lhs, rhs)},
    {"name": "var", "symbols": ["WORD"], "postprocess": id},
    {"name": "scene$ebnf$1", "symbols": ["sceneHeading"], "postprocess": id},
    {"name": "scene$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "scene$ebnf$2", "symbols": ["shot"]},
    {"name": "scene$ebnf$2", "symbols": ["scene$ebnf$2", "shot"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "scene", "symbols": ["scene$ebnf$1", "scene$ebnf$2"]},
    {"name": "sceneHeading$ebnf$1", "symbols": [{"literal":"."}], "postprocess": id},
    {"name": "sceneHeading$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "sceneHeading$ebnf$2", "symbols": ["comment"], "postprocess": id},
    {"name": "sceneHeading$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "sceneHeading$ebnf$3", "symbols": ["NL"]},
    {"name": "sceneHeading$ebnf$3", "symbols": ["sceneHeading$ebnf$3", "NL"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "sceneHeading", "symbols": ["SCENE_PLACEMENT", "sceneHeading$ebnf$1", "_", "sceneName", "_", "SHOTSEP", "_", "TIME_OF_DAY", "sceneHeading$ebnf$2", "sceneHeading$ebnf$3"]},
    {"name": "sceneName$ebnf$1$subexpression$1", "symbols": ["_", "WORD", "_"]},
    {"name": "sceneName$ebnf$1", "symbols": ["sceneName$ebnf$1$subexpression$1"]},
    {"name": "sceneName$ebnf$1$subexpression$2", "symbols": ["_", "WORD", "_"]},
    {"name": "sceneName$ebnf$1", "symbols": ["sceneName$ebnf$1", "sceneName$ebnf$1$subexpression$2"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "sceneName", "symbols": ["sceneName$ebnf$1"]},
    {"name": "shot$ebnf$1", "symbols": ["shotHeading"], "postprocess": id},
    {"name": "shot$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "shot$ebnf$2", "symbols": ["NL"]},
    {"name": "shot$ebnf$2", "symbols": ["shot$ebnf$2", "NL"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "shot$ebnf$3$subexpression$1", "symbols": ["action"]},
    {"name": "shot$ebnf$3$subexpression$1", "symbols": ["dialogue"]},
    {"name": "shot$ebnf$3", "symbols": ["shot$ebnf$3$subexpression$1"]},
    {"name": "shot$ebnf$3$subexpression$2", "symbols": ["action"]},
    {"name": "shot$ebnf$3$subexpression$2", "symbols": ["dialogue"]},
    {"name": "shot$ebnf$3", "symbols": ["shot$ebnf$3", "shot$ebnf$3$subexpression$2"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "shot$ebnf$4", "symbols": ["comment"], "postprocess": id},
    {"name": "shot$ebnf$4", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "shot", "symbols": ["shot$ebnf$1", "shot$ebnf$2", "shot$ebnf$3", "shot$ebnf$4"]},
    {"name": "shotHeading$ebnf$1$subexpression$1", "symbols": ["_", "SHOTSEP", "_", "shotSource", "_"]},
    {"name": "shotHeading$ebnf$1", "symbols": ["shotHeading$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "shotHeading$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "shotHeading$ebnf$2$subexpression$1", "symbols": ["_", "SHOTSEP", "_", "shotTarget", "_"]},
    {"name": "shotHeading$ebnf$2", "symbols": ["shotHeading$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "shotHeading$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "shotHeading$ebnf$3$subexpression$1", "symbols": ["_", "SHOTSEP", "_", "SHOT_MOVEMENT", "_"]},
    {"name": "shotHeading$ebnf$3", "symbols": ["shotHeading$ebnf$3$subexpression$1"], "postprocess": id},
    {"name": "shotHeading$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "shotHeading$subexpression$1$ebnf$1", "symbols": ["comment"], "postprocess": id},
    {"name": "shotHeading$subexpression$1$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "shotHeading$subexpression$1", "symbols": ["shotHeading$subexpression$1$ebnf$1"]},
    {"name": "shotHeading$subexpression$1$ebnf$2", "symbols": ["NL"]},
    {"name": "shotHeading$subexpression$1$ebnf$2", "symbols": ["shotHeading$subexpression$1$ebnf$2", "NL"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "shotHeading$subexpression$1", "symbols": ["shotHeading$subexpression$1$ebnf$2"]},
    {"name": "shotHeading", "symbols": ["SHOT_TYPE", "shotHeading$ebnf$1", "shotHeading$ebnf$2", "shotHeading$ebnf$3", "_", "SHOTSEP", "_", "TIME", "shotHeading$subexpression$1"]},
    {"name": "action$ebnf$1", "symbols": ["SENTENCE"]},
    {"name": "action$ebnf$1", "symbols": ["action$ebnf$1", "SENTENCE"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "action", "symbols": ["action$ebnf$1"]},
    {"name": "TIME", "symbols": ["unsigned_int", "unsigned_int", {"literal":":"}, "unsigned_int", "unsigned_int"]},
    {"name": "unsigned_int$ebnf$1", "symbols": [/[0-9]/]},
    {"name": "unsigned_int$ebnf$1", "symbols": ["unsigned_int$ebnf$1", /[0-9]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "unsigned_int", "symbols": ["unsigned_int$ebnf$1"], "postprocess": 
        function(d) {
            return parseInt(d[0].join(""));
        }
        },
    {"name": "shotSource", "symbols": ["shotSubject"]},
    {"name": "shotTarget", "symbols": ["shotSubject"]},
    {"name": "shotSubject$ebnf$1", "symbols": []},
    {"name": "shotSubject$ebnf$1$subexpression$1", "symbols": ["_", "SHOT_SUBJECT_SEP", "_", "WORD"]},
    {"name": "shotSubject$ebnf$1", "symbols": ["shotSubject$ebnf$1", "shotSubject$ebnf$1$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "shotSubject", "symbols": ["WORD", "shotSubject$ebnf$1"]},
    {"name": "dialogue$ebnf$1", "symbols": ["SENTENCE"]},
    {"name": "dialogue$ebnf$1", "symbols": ["dialogue$ebnf$1", "SENTENCE"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "dialogue", "symbols": ["speakerName", {"literal":":"}, "dialogue$ebnf$1"]},
    {"name": "speakerName$ebnf$1$subexpression$1$ebnf$1", "symbols": [{"literal":"."}], "postprocess": id},
    {"name": "speakerName$ebnf$1$subexpression$1$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "speakerName$ebnf$1$subexpression$1$ebnf$2", "symbols": [{"literal":"-"}], "postprocess": id},
    {"name": "speakerName$ebnf$1$subexpression$1$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "speakerName$ebnf$1$subexpression$1", "symbols": ["_", "WORD", "speakerName$ebnf$1$subexpression$1$ebnf$1", "speakerName$ebnf$1$subexpression$1$ebnf$2", "_"]},
    {"name": "speakerName$ebnf$1", "symbols": ["speakerName$ebnf$1$subexpression$1"]},
    {"name": "speakerName$ebnf$1$subexpression$2$ebnf$1", "symbols": [{"literal":"."}], "postprocess": id},
    {"name": "speakerName$ebnf$1$subexpression$2$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "speakerName$ebnf$1$subexpression$2$ebnf$2", "symbols": [{"literal":"-"}], "postprocess": id},
    {"name": "speakerName$ebnf$1$subexpression$2$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "speakerName$ebnf$1$subexpression$2", "symbols": ["_", "WORD", "speakerName$ebnf$1$subexpression$2$ebnf$1", "speakerName$ebnf$1$subexpression$2$ebnf$2", "_"]},
    {"name": "speakerName$ebnf$1", "symbols": ["speakerName$ebnf$1", "speakerName$ebnf$1$subexpression$2"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "speakerName", "symbols": ["speakerName$ebnf$1"]},
    {"name": "val", "symbols": ["BOOL"]},
    {"name": "fromTransition", "symbols": ["_", "TRANSITION_TYPE", {"literal":":"}, "_"]},
    {"name": "toTransition", "symbols": ["_", "TRANSITION_TYPE", {"literal":":"}, "_"]},
    {"name": "_$ebnf$1", "symbols": []},
    {"name": "_$ebnf$1", "symbols": ["_$ebnf$1", "wschar"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "_", "symbols": ["_$ebnf$1"], "postprocess": () => null},
    {"name": "__$ebnf$1", "symbols": ["wschar"]},
    {"name": "__$ebnf$1", "symbols": ["__$ebnf$1", "wschar"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "__", "symbols": ["__$ebnf$1"], "postprocess": () => null},
    {"name": "wschar", "symbols": [/[ ]/], "postprocess": id},
    {"name": "NL", "symbols": [{"literal":"\r"}, {"literal":"\n"}]},
    {"name": "NL", "symbols": [{"literal":"\r"}]},
    {"name": "NL", "symbols": [{"literal":"\n"}], "postprocess": id},
    {"name": "TAB", "symbols": [/[\t]/], "postprocess": id},
    {"name": "comment$string$1", "symbols": [{"literal":"/"}, {"literal":"/"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "comment$ebnf$1", "symbols": []},
    {"name": "comment$ebnf$1", "symbols": ["comment$ebnf$1", /./], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "comment", "symbols": ["_", "comment$string$1", "comment$ebnf$1"], "postprocess": () => null},
    {"name": "SHOT_MOVEMENT$string$1", "symbols": [{"literal":"S"}, {"literal":"T"}, {"literal":"E"}, {"literal":"A"}, {"literal":"D"}, {"literal":"I"}, {"literal":"C"}, {"literal":"A"}, {"literal":"M"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SHOT_MOVEMENT", "symbols": ["SHOT_MOVEMENT$string$1"]},
    {"name": "SHOT_MOVEMENT$string$2", "symbols": [{"literal":"H"}, {"literal":"A"}, {"literal":"N"}, {"literal":"D"}, {"literal":"H"}, {"literal":"E"}, {"literal":"L"}, {"literal":"D"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SHOT_MOVEMENT", "symbols": ["SHOT_MOVEMENT$string$2"]},
    {"name": "SHOT_MOVEMENT$string$3", "symbols": [{"literal":"P"}, {"literal":"O"}, {"literal":"V"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SHOT_MOVEMENT", "symbols": ["SHOT_MOVEMENT$string$3"]},
    {"name": "SHOT_MOVEMENT$string$4", "symbols": [{"literal":"P"}, {"literal":"."}, {"literal":"O"}, {"literal":"."}, {"literal":"V"}, {"literal":"."}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SHOT_MOVEMENT", "symbols": ["SHOT_MOVEMENT$string$4"]},
    {"name": "SHOT_MOVEMENT$string$5", "symbols": [{"literal":"E"}, {"literal":"A"}, {"literal":"S"}, {"literal":"E"}, {"literal":" "}, {"literal":"I"}, {"literal":"N"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SHOT_MOVEMENT", "symbols": ["SHOT_MOVEMENT$string$5"]},
    {"name": "SENTENCE$ebnf$1", "symbols": []},
    {"name": "SENTENCE$ebnf$1", "symbols": ["SENTENCE$ebnf$1", /./], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "SENTENCE$ebnf$2", "symbols": [/[.?!\n]/]},
    {"name": "SENTENCE$ebnf$2", "symbols": ["SENTENCE$ebnf$2", /[.?!\n]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "SENTENCE", "symbols": ["SENTENCE$ebnf$1", "SENTENCE$ebnf$2", "_"]},
    {"name": "WORD$ebnf$1", "symbols": [/[a-zA-Z]/]},
    {"name": "WORD$ebnf$1", "symbols": ["WORD$ebnf$1", /[a-zA-Z]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "WORD", "symbols": ["WORD$ebnf$1"]},
    {"name": "INPUT$string$1", "symbols": [{"literal":"T"}, {"literal":"O"}, {"literal":"U"}, {"literal":"C"}, {"literal":"H"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INPUT", "symbols": ["INPUT$string$1"]},
    {"name": "INPUT$string$2", "symbols": [{"literal":"S"}, {"literal":"W"}, {"literal":"I"}, {"literal":"P"}, {"literal":"E"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INPUT", "symbols": ["INPUT$string$2"]},
    {"name": "INPUT$string$3", "symbols": [{"literal":"T"}, {"literal":"A"}, {"literal":"P"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "INPUT", "symbols": ["INPUT$string$3"]},
    {"name": "BOOL$string$1", "symbols": [{"literal":"T"}, {"literal":"R"}, {"literal":"U"}, {"literal":"E"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "BOOL", "symbols": ["BOOL$string$1"]},
    {"name": "BOOL$string$2", "symbols": [{"literal":"F"}, {"literal":"A"}, {"literal":"L"}, {"literal":"S"}, {"literal":"E"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "BOOL", "symbols": ["BOOL$string$2"]},
    {"name": "TRANSITION_TYPE$string$1", "symbols": [{"literal":"F"}, {"literal":"A"}, {"literal":"D"}, {"literal":"E"}, {"literal":" "}, {"literal":"O"}, {"literal":"U"}, {"literal":"T"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TRANSITION_TYPE", "symbols": ["TRANSITION_TYPE$string$1"]},
    {"name": "TRANSITION_TYPE$string$2", "symbols": [{"literal":"F"}, {"literal":"A"}, {"literal":"D"}, {"literal":"E"}, {"literal":" "}, {"literal":"I"}, {"literal":"N"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TRANSITION_TYPE", "symbols": ["TRANSITION_TYPE$string$2"]},
    {"name": "TRANSITION_TYPE$string$3", "symbols": [{"literal":"C"}, {"literal":"U"}, {"literal":"T"}, {"literal":" "}, {"literal":"T"}, {"literal":"O"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TRANSITION_TYPE", "symbols": ["TRANSITION_TYPE$string$3"]},
    {"name": "SCENE_PLACEMENT$string$1", "symbols": [{"literal":"I"}, {"literal":"N"}, {"literal":"T"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SCENE_PLACEMENT", "symbols": ["SCENE_PLACEMENT$string$1"]},
    {"name": "SCENE_PLACEMENT$string$2", "symbols": [{"literal":"E"}, {"literal":"X"}, {"literal":"T"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SCENE_PLACEMENT", "symbols": ["SCENE_PLACEMENT$string$2"]},
    {"name": "SCENE_PLACEMENT$string$3", "symbols": [{"literal":"I"}, {"literal":"N"}, {"literal":"T"}, {"literal":"/"}, {"literal":"E"}, {"literal":"X"}, {"literal":"T"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SCENE_PLACEMENT", "symbols": ["SCENE_PLACEMENT$string$3"]},
    {"name": "SCENE_PLACEMENT$string$4", "symbols": [{"literal":"E"}, {"literal":"X"}, {"literal":"T"}, {"literal":"/"}, {"literal":"I"}, {"literal":"N"}, {"literal":"T"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SCENE_PLACEMENT", "symbols": ["SCENE_PLACEMENT$string$4"]},
    {"name": "TIME_OF_DAY$string$1", "symbols": [{"literal":"D"}, {"literal":"A"}, {"literal":"Y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TIME_OF_DAY", "symbols": ["TIME_OF_DAY$string$1"]},
    {"name": "TIME_OF_DAY$string$2", "symbols": [{"literal":"N"}, {"literal":"I"}, {"literal":"G"}, {"literal":"H"}, {"literal":"T"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TIME_OF_DAY", "symbols": ["TIME_OF_DAY$string$2"]},
    {"name": "TIME_OF_DAY$string$3", "symbols": [{"literal":"M"}, {"literal":"O"}, {"literal":"R"}, {"literal":"N"}, {"literal":"I"}, {"literal":"N"}, {"literal":"G"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TIME_OF_DAY", "symbols": ["TIME_OF_DAY$string$3"]},
    {"name": "TIME_OF_DAY$string$4", "symbols": [{"literal":"N"}, {"literal":"O"}, {"literal":"O"}, {"literal":"N"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TIME_OF_DAY", "symbols": ["TIME_OF_DAY$string$4"]},
    {"name": "TIME_OF_DAY$string$5", "symbols": [{"literal":"A"}, {"literal":"F"}, {"literal":"T"}, {"literal":"E"}, {"literal":"R"}, {"literal":"N"}, {"literal":"O"}, {"literal":"O"}, {"literal":"N"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TIME_OF_DAY", "symbols": ["TIME_OF_DAY$string$5"]},
    {"name": "TIME_OF_DAY$string$6", "symbols": [{"literal":"D"}, {"literal":"U"}, {"literal":"S"}, {"literal":"K"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TIME_OF_DAY", "symbols": ["TIME_OF_DAY$string$6"]},
    {"name": "TIME_OF_DAY$string$7", "symbols": [{"literal":"E"}, {"literal":"V"}, {"literal":"E"}, {"literal":"N"}, {"literal":"I"}, {"literal":"N"}, {"literal":"G"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TIME_OF_DAY", "symbols": ["TIME_OF_DAY$string$7"]},
    {"name": "TIME_OF_DAY$string$8", "symbols": [{"literal":"D"}, {"literal":"A"}, {"literal":"W"}, {"literal":"N"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "TIME_OF_DAY", "symbols": ["TIME_OF_DAY$string$8"]},
    {"name": "SHOT_SUBJECT_SEP", "symbols": [{"literal":"/"}]},
    {"name": "SHOT_TYPE$string$1", "symbols": [{"literal":"M"}, {"literal":"C"}, {"literal":"U"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SHOT_TYPE", "symbols": ["SHOT_TYPE$string$1"]},
    {"name": "SHOT_TYPE$string$2", "symbols": [{"literal":"C"}, {"literal":"U"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SHOT_TYPE", "symbols": ["SHOT_TYPE$string$2"]},
    {"name": "SHOT_TYPE$string$3", "symbols": [{"literal":"E"}, {"literal":"W"}, {"literal":"S"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SHOT_TYPE", "symbols": ["SHOT_TYPE$string$3"]},
    {"name": "SHOT_TYPE$string$4", "symbols": [{"literal":"M"}, {"literal":"E"}, {"literal":"D"}, {"literal":" "}, {"literal":"S"}, {"literal":"H"}, {"literal":"O"}, {"literal":"T"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "SHOT_TYPE", "symbols": ["SHOT_TYPE$string$4"]},
    {"name": "AWAIT$string$1", "symbols": [{"literal":"A"}, {"literal":"W"}, {"literal":"A"}, {"literal":"I"}, {"literal":"T"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "AWAIT", "symbols": ["AWAIT$string$1"]},
    {"name": "AND$string$1", "symbols": [{"literal":"&"}, {"literal":"&"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "AND", "symbols": ["AND$string$1"]},
    {"name": "OR$string$1", "symbols": [{"literal":"|"}, {"literal":"|"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "OR", "symbols": ["OR$string$1"]},
    {"name": "SHOTSEP", "symbols": [{"literal":"-"}]}
]
  , ParserStart: "start"
}
if (typeof module !== 'undefined'&& typeof module.exports !== 'undefined') {
   module.exports = grammar;
} else {
   window.grammar = grammar;
}
})();
